### ISSUE TITLE
1.7.5: download plugin checks-api to file: status code: 403, reason phrase: Forbidden

### ISSUE THREAD

**Issue by brovoca** [jenkinsci/checks-api-plugin#183]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  jenkins/jenkins:2.319.3
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Kubernetes

### Reproduction steps

```sh
jenkins-plugin-cli --verbose \
    --war "$JENKINS_WAR" \
    --plugin-download-directory "$JENKINS_HOME/plugins" \
    --plugins "artifactory cloudbees-disk-usage-simple cloudbees-folder config-file-provider configuration-as-code credentials gerrit-trigger git mailer matrix-auth prometheus saml simple-theme-plugin ssh-slaves" \
    --latest "false"
```

### Expected Results

checks-api 1.7.5 should be available at https://archives.jenkins.io/plugins/checks-api/1.7.5/checks-api.hpi

### Actual Results

```log
...
Downloaded gradle from https://mirror.gruenehoelle.nl/jenkins/plugins/gradle/1.39.4/gradle.hpi (attempt 1 of 3)
Downloaded and validated plugin gradle
Checksum valid for: gradle
Downloaded artifactory from https://mirror.gruenehoelle.nl/jenkins/plugins/artifactory/3.17.0/artifactory.hpi (attempt 1 of 3)
Downloaded and validated plugin artifactory
Checksum valid for: artifactory
Unable to resolve plugin URL https://archives.jenkins.io/plugins/checks-api/1.7.5/checks-api.hpi, or download plugin checks-api to file: status code: 403, reason phrase: Forbidden
io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to download checks-api
    at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$downloadPlugins$4(PluginManager.java:565)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
    at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Unable to download checks-api
```

### Anything else?

Manually installing checks-api worked as it somehow resolved another endpoint to fetch it from.

```log
# jenkins-plugin-cli --verbose --war "$JENKINS_WAR" --plugin-download-directory "$JENKINS_HOME/plugins" --plugins "checks-api" --latest "false"
...
Checksum valid for: script-security
Downloaded caffeine-api from https://mirror.gruenehoelle.nl/jenkins/plugins/caffeine-api/2.9.1-23.v51c4e2c879c8/caffeine-api.hpi (attempt 1 of 3)
Downloaded and validated plugin caffeine-api
Downloaded plugin-util-api from https://mirror.gruenehoelle.nl/jenkins/plugins/plugin-util-api/2.17.0/plugin-util-api.hpi (attempt 1 of 3)
Downloaded and validated plugin plugin-util-api
Checksum valid for: caffeine-api
Checksum valid for: plugin-util-api
Downloaded checks-api from https://ftp-nyc.osuosl.org/pub/jenkins/plugins/checks-api/1.7.5/checks-api.hpi (attempt 1 of 3)
Downloaded and validated plugin checks-api
Checksum valid for: checks-api
Done
```

**Comment by timja** [comment]
Please raise this on https://github.com/jenkins-infra/helpdesk

**Comment by brovoca** [comment]
Done https://github.com/jenkins-infra/helpdesk/issues/3095
